#pragma once

#define ZT_PARAM_AI_KEY                         0
#define ZT_PARAM_AI_URL                         1
#define ZT_PARAM_AI_PROP                        2
#define ZT_PARAM_AI_FONT                        3
#define ZT_PARAM_AI_SIZE                        4
#define ZT_PARAM_AI_TIMEOUT                     5
#define ZT_PARAM_AI_PROXY_TYPE                  6
#define ZT_PARAM_AI_PROXY                       7
#define ZT_PARAM_AI_PUB_KEY                     8
#define ZT_PARAM_AI_SEC_KEY                     9
#define ZT_PARAM_AI_DATACACHE                   10

#define ZT_PARAM_TTY_AUTO_WRAP                  10
#define ZT_PARAM_TTY_DEC_ORIGIN_MODE            11
#define ZT_PARAM_TTY_IMPLICT_CR_LF              12
#define ZT_PARAM_TTY_IMPLICT_LF_CR              13
#define ZT_PARAM_TTY_BACKGROUND_COLOR           14
#define ZT_PARAM_TTY_ENABLE_BLINK_TEXT          15
#define ZT_PARAM_TTY_ANSWERBACK_TO_E            16
#define ZT_PARAM_TTY_LOCAL_ECHO                 17
#define ZT_PARAM_TTY_LOCAL_LINE_EDITING         18
#define ZT_PARAM_TTY_PRINTER_ANSI               19

#define ZT_PARAM_TTY_KEYBOARD_BACKSPACE_KEY     20
#define ZT_PARAM_TTY_KEYBOARD_HOME_END_KEYS     21
#define ZT_PARAM_TTY_KEYBOARD_FUNCTION_KEY      22
#define ZT_PARAM_TTY_KEYBOARD_SCA_ARROW_KEY     23
#define ZT_PARAM_TTY_KEYBOARD_CURSOR_KEYS       24
#define ZT_PARAM_TTY_KEYBOARD_NUMERIC_KEYS      25
#define ZT_PARAM_TTY_KEYBOARD_COMPOSE_KEY       26
#define ZT_PARAM_TTY_KEYBOARD_CTRL_ALT_DIFF     27

#define ZT_PARAM_TTY_BELL_ACTION_FOR_BELL       30
#define ZT_PARAM_TTY_BELL_SOUND_FILE            31
#define ZT_PARAM_TTY_BELL_TASKBAR_CAPTION       32
#define ZT_PARAM_TTY_BELL_DISABLE_OVERUSED      33
#define ZT_PARAM_TTY_BELL_OVERUSE_TIME          34
#define ZT_PARAM_TTY_BELL_OVERUSE_TIME_SECOND   35
#define ZT_PARAM_TTY_BELL_SECONDS_SILENCE       36

#define ZT_PARAM_TTY_FEATURES_APP_CURSOR        40
#define ZT_PARAM_TTY_FEATURES_APP_KEYPAD        41
#define ZT_PARAM_TTY_FEATURES_XTERM_MOUSE       42
#define ZT_PARAM_TTY_FEATURES_REMOTE_SIZING     43
#define ZT_PARAM_TTY_FEATURES_SWITCH_SCREEN     44
#define ZT_PARAM_TTY_FEATURES_REMOTE_TITLE      45
#define ZT_PARAM_TTY_FEATURES_REMOTE_GUERY      46
#define ZT_PARAM_TTY_FEATURES_REMOTE_CLEAR      47
#define ZT_PARAM_TTY_FEATURES_BACKSPACE_SERVER  48
#define ZT_PARAM_TTY_FEATURES_REMOTE_CONFIG     49
#define ZT_PARAM_TTY_FEATURES_ARABIC_TEXT       50
#define ZT_PARAM_TTY_FEATURES_BIDIRECT_TEXT     51

#define ZT_PARAM_WINDOW_COLUMNS                 60
#define ZT_PARAM_WINDOW_ROWS                    61
#define ZT_PARAM_WINDOW_RESIZED_ACTION          62
#define ZT_PARAM_WINDOW_LINE_SCROLLBACK         63
#define ZT_PARAM_WINDOW_DISPLAY_SCROLLBAR       64
#define ZT_PARAM_WINDOW_FULLSCREEN_SCROLLBAR    65
#define ZT_PARAM_WINDOW_RESET_SCROLLBAR_KEY     66
#define ZT_PARAM_WINDOW_RESET_SCROLLBAR_DISPLAY 67
#define ZT_PARAM_WINDOW_ERASED_TEXT_SCROLLBAR   68

#define ZT_PARAM_WINDOW_APPEARANCE_CURSOR_TYPE  70
#define ZT_PARAM_WINDOW_APPEARANCE_CURSOR_BLINK 71
#define ZT_PARAM_WINDOW_APPEARANCE_FONT_NAME    72
#define ZT_PARAM_WINDOW_APPEARANCE_FONT_SIZE    73
#define ZT_PARAM_WINDOW_APPEARANCE_PITCH_FONT   74
#define ZT_PARAM_WINDOW_APPEARANCE_GUALITY      75
#define ZT_PARAM_WINDOW_APPEARANCE_HIDE_MOUSE   76
#define ZT_PARAM_WINDOW_APPEARANCE_GAP_TEXT_WIN 77
#define ZT_PARAM_WINDOW_APPEARANCE_SUNKEN_EDGE  78

#define ZT_PARAM_WINDOW_BEHAVIOUR_WINDOW_TITLE  80
#define ZT_PARAM_WINDOW_BEHAVIOUR_1             
#define ZT_PARAM_WINDOW_BEHAVIOUR_2
#define ZT_PARAM_WINDOW_BEHAVIOUR_3
#define ZT_PARAM_WINDOW_BEHAVIOUR_4
#define ZT_PARAM_WINDOW_BEHAVIOUR_5
#define ZT_PARAM_WINDOW_BEHAVIOUR_6
#define ZT_PARAM_WINDOW_BEHAVIOUR_7

#define ZT_PARAM_WINDOW_TRANSLATION_1
#define ZT_PARAM_WINDOW_TRANSLATION_2
#define ZT_PARAM_WINDOW_TRANSLATION_3
#define ZT_PARAM_WINDOW_TRANSLATION_4
#define ZT_PARAM_WINDOW_TRANSLATION_5
#define ZT_PARAM_WINDOW_TRANSLATION_6

#define ZT_PARAM_WINDOW_SELECTION_1
#define ZT_PARAM_WINDOW_SELECTION_2
#define ZT_PARAM_WINDOW_SELECTION_3
#define ZT_PARAM_WINDOW_SELECTION_4
#define ZT_PARAM_WINDOW_SELECTION_5
#define ZT_PARAM_WINDOW_SELECTION_6
#define ZT_PARAM_WINDOW_SELECTION_7
#define ZT_PARAM_WINDOW_SELECTION_8

#define ZT_PARAM_WINDOW_SELECTION_COPY_1
#define ZT_PARAM_WINDOW_SELECTION_COPY_2
#define ZT_PARAM_WINDOW_SELECTION_COPY_3

#define ZT_PARAM_WINDOW_COLOURS_1
#define ZT_PARAM_WINDOW_COLOURS_2
#define ZT_PARAM_WINDOW_COLOURS_3
#define ZT_PARAM_WINDOW_COLOURS_4
#define ZT_PARAM_WINDOW_COLOURS_5
#define ZT_PARAM_WINDOW_COLOURS_6
#define ZT_PARAM_WINDOW_COLOURS_7
#define ZT_PARAM_WINDOW_COLOURS_8
#define ZT_PARAM_WINDOW_COLOURS_9
#define ZT_PARAM_WINDOW_COLOURS_10
